name: dem_0_1_0_rc2
channels:
  - conda-forge
  - https://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - alabaster=0.7.16=pyhd8ed1ab_0
  - arrow=1.3.0=pyhd8ed1ab_0
  - arrow-cpp=14.0.2=h374c478_1
  - astroid=2.14.2=py39h06a4308_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - atomicwrites=1.4.1=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - autopep8=2.0.4=pyhd8ed1ab_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - babel=2.14.0=pyhd8ed1ab_0
  - bcrypt=3.2.0=py39h5eee18b_1
  - beautifulsoup4=4.12.3=pyha770c72_0
  - binaryornot=0.4.4=py_1
  - black=23.11.0=py39h06a4308_0
  - blas=1.0=mkl
  - bleach=6.1.0=pyhd8ed1ab_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.8=py39h44dd56e_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py39h6a678d5_7
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.27.0=hd590300_0
  - ca-certificates=2024.7.2=h06a4308_0
  - calliope=0.6.10=pyhd8ed1ab_1
  - certifi=2024.7.4=py39h06a4308_0
  - cffi=1.16.0=py39h5eee18b_0
  - cftime=1.6.3=py39h44dd56e_0
  - chardet=4.0.0=py39h06a4308_1003
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py39hdb19cb5_0
  - cookiecutter=2.6.0=pyhca7485f_0
  - cryptography=42.0.5=py39hdda0065_0
  - curl=8.5.0=hdbd6064_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py39h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - diff-match-patch=20230430=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - docstring-to-markdown=0.15=pyhd8ed1ab_0
  - docutils=0.18.1=py39h06a4308_3
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=py39h06a4308_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h59595ed_0
  - flake8=6.0.0=py39h06a4308_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h0708190_1
  - gflags=2.2.2=h6a678d5_1
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.5.0=h6a678d5_1
  - grpc-cpp=1.48.2=he1ff14a_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.10.6=nompi_h3c11f04_101
  - icu=73.1=h6a678d5_0
  - idna=3.6=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=7.0.2=pyha770c72_0
  - importlib_metadata=7.0.2=hd8ed1ab_0
  - importlib_resources=6.3.0=pyhd8ed1ab_0
  - inflection=0.5.1=pyh9f0ad1d_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipdb=0.13.13=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.18.1=pyh707e725_3
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - isort=5.13.2=pyhd8ed1ab_0
  - jaraco.classes=3.3.1=pyhd8ed1ab_0
  - jedi=0.18.1=py39h06a4308_1
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jellyfish=1.0.1=py39hb02cf49_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - jsonschema=4.21.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py39h06a4308_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - keyring=24.3.1=py39h06a4308_0
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lazy-object-proxy=1.6.0=py39h27cfd23_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=1_h6e990d7_netlib
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcblas=3.9.0=3_h893e4fe_netlib
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.5.0=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libglib=2.78.4=hdc74915_0
  - libgomp=13.2.0=h807b86a_5
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=3_h893e4fe_netlib
  - libllvm14=14.0.6=hdb19cb5_3
  - libnetcdf=4.8.1=nompi_hcd642e3_100
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libssh2=1.10.0=ha35d2d1_2
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.16=hd590300_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.10.4=hf1b16e4_1
  - libzip=1.8.0=h1c5bbd1_1
  - lz4-c=1.9.4=h6a678d5_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py39h5eee18b_0
  - matplotlib=3.8.0=py39h06a4308_0
  - matplotlib-base=3.8.0=py39h1128e8f_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - more-itertools=10.2.0=pyhd8ed1ab_0
  - munkres=1.1.4=py_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - mysql=5.7.20=hf484d3e_1001
  - natsort=8.4.0=pyhd8ed1ab_0
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert=7.16.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.2=pyhd8ed1ab_0
  - nbconvert-pandoc=7.16.2=pyhd8ed1ab_0
  - nbformat=5.10.2=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - netcdf4=1.5.7=nompi_py39hd2e3950_101
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.7.3=py39hde0f152_1
  - numpy-base=1.23.5=py39h060ed82_1
  - numpydoc=1.6.0=pyhd8ed1ab_0
  - openjpeg=2.4.0=h3ad879b_0
  - openpyxl=3.1.5=py39h5eee18b_0
  - openssl=3.2.1=hd590300_0
  - orc=1.7.4=hb3bc3d3_1
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=1.5.3=py39h2ad29b5_1
  - pandoc=3.1.12.2=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.12.1=pyhd8ed1ab_0
  - pcre2=10.42=hebb0a14_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.2.0=py39h5eee18b_0
  - pip=23.3.1=py39h06a4308_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - pluggy=1.4.0=pyhd8ed1ab_0
  - ply=3.11=py39h06a4308_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.0=py39h5eee18b_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=14.0.2=py39h1eedbd7_0
  - pycodestyle=2.10.0=py39h06a4308_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydocstyle=6.3.0=pyhd8ed1ab_0
  - pyflakes=3.0.1=py39h06a4308_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pylint=2.16.2=py39h06a4308_0
  - pylint-venv=3.0.3=pyhd8ed1ab_0
  - pyls-spyder=0.4.0=pyhd8ed1ab_0
  - pynacl=1.5.0=py39h5eee18b_0
  - pyomo=6.4.4=py39h227be39_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pyqt=5.15.10=py39h6a678d5_0
  - pyqt5-sip=12.13.0=py39h5eee18b_0
  - pyqtwebengine=5.15.10=py39h6a678d5_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.18=h955ad1f_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-lsp-black=2.0.0=pyhd8ed1ab_0
  - python-lsp-jsonrpc=1.1.2=pyhd8ed1ab_0
  - python-lsp-server=1.7.2=py39h06a4308_0
  - python-lsp-server-base=1.10.1=pyhd8ed1ab_0
  - python-slugify=8.0.4=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytoolconfig=1.2.5=pyhd8ed1ab_0
  - pytz=2024.1=pyhd8ed1ab_0
  - pyxdg=0.28=pyhd8ed1ab_0
  - pyyaml=6.0.1=py39h5eee18b_0
  - pyzmq=25.1.2=py39h6a678d5_0
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.2.2=pyhd8ed1ab_0
  - qt-main=5.15.2=h53bd1ea_10
  - qt-webengine=5.15.9=h9ab4d14_7
  - qtawesome=1.2.3=pyhd8ed1ab_0
  - qtconsole=5.4.2=py39h06a4308_0
  - qtconsole-base=5.5.1=pyha770c72_0
  - qtpy=2.4.1=pyhd8ed1ab_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - referencing=0.33.0=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - retrying=1.3.3=py_2
  - rich=13.7.1=pyhd8ed1ab_0
  - rope=1.12.0=pyhd8ed1ab_0
  - rpds-py=0.10.6=py39hb02cf49_0
  - rtree=1.0.1=py39h06a4308_0
  - ruamel.yaml=0.17.40=py39hd1e30aa_0
  - ruamel.yaml.clib=0.2.8=py39hd1e30aa_0
  - s2n=1.3.27=hdbd6064_0
  - scikit-learn=1.2.2=py39h6a678d5_1
  - scipy=1.5.3=py39hf3f25e7_0
  - secretstorage=3.3.1=py39h06a4308_1
  - setuptools=68.2.2=py39h06a4308_0
  - sip=6.7.12=py39h6a678d5_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h6a678d5_1
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sphinx=7.2.6=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.8=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.6=pyhd8ed1ab_0
  - sphinxcontrib-htmlhelp=2.0.5=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_0
  - sphinxcontrib-qthelp=1.0.7=pyhd8ed1ab_0
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_0
  - spyder=5.4.3=py39h06a4308_1
  - spyder-kernels=2.4.4=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - text-unidecode=1.3=pyhd8ed1ab_1
  - textdistance=4.5.0=pyhd8ed1ab_0
  - threadpoolctl=3.3.0=pyhc1e730c_0
  - three-merge=0.1.1=pyh9f0ad1d_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.12.4=pyha770c72_0
  - tornado=6.3.3=py39h5eee18b_0
  - traitlets=5.14.2=pyhd8ed1ab_0
  - types-python-dateutil=2.8.19.20240311=pyhd8ed1ab_0
  - typing-extensions=4.10.0=hd8ed1ab_0
  - typing_extensions=4.10.0=pyha770c72_0
  - tzdata=2024a=h04d1e81_0
  - ujson=5.4.0=py39h6a678d5_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - utf8proc=2.6.1=h5eee18b_1
  - watchdog=2.1.6=py39h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - whatthepatch=1.0.5=pyhd8ed1ab_0
  - wheel=0.41.2=py39h06a4308_0
  - wrapt=1.14.1=py39h5eee18b_0
  - wurlitzer=3.0.3=pyhd8ed1ab_0
  - xarray=2022.3.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - concave-hull==0.0.7
      - kaleido==0.2.1
      - meteostat==1.6.7
      - numpy==1.22.4
      - patsy==0.5.6
      - plotly==5.20.0
      - plotly-express==0.4.1
      - statsmodels==0.14.1
      - tenacity==8.2.3
      - triangle==20230923
